final List hotelList = [
  {
    'title': 'Onomo Hotel Lomé',
    'place': 'Boulevard du Mono, Lomé-TOGO',
    'distance': 2,
    'picture': 'assets/images/onomo1.jpg',
    'review': 36,
    'price': '250.000',
  },
  {
    'title': 'Hotel Sarakawa Lomé',
    'place': 'Boulevard du Mono, Lomé-TOGO',
    'distance': 2.5,
    'picture': 'assets/images/hotel1.jpeg',
    'review': 36,
    'price': '250.000',
  },
  {
    'title': 'Hôtel 2 Février',
    'place': 'Boulevard du Mono, Lomé-TOGO',
    'distance': 2.5,
    'picture': 'assets/images/2feb1.jpg',
    'review': 36,
    'price': '250.000',
  },
  {
    'title': 'Onomo Hotel Lomé',
    'place': 'Boulevard du Mono, Lomé-TOGO',
    'distance': 2.5,
    'picture': 'assets/images/hotel1.jpeg',
    'review': 36,
    'price': '250.000',
  },
  {
    'title': 'Onomo Hotel Lomé',
    'place': 'Boulevard du Mono, Lomé-TOGO',
    'distance': 2.5,
    'picture': 'assets/images/hotel1.jpeg',
    'review': 36,
    'price': '250.000',
  },
  {
    'title': 'Onomo Hotel Lomé',
    'place': 'Boulevard du Mono, Lomé-TOGO',
    'distance': 2.5,
    'picture': 'assets/images/hotel1.jpeg',
    'review': 36,
    'price': '250.000',
  },
];
